// Graphstore namespace — Phase 4 Dolt-like versioned graph storage.
//
// Re-exports the public surface of `codragraph-graphstore` so SDK users
// don't need a second install. See codragraph-graphstore/RFC.md for the
// full design.

export {
  type ObjectId,
  type SchemaVersion,
  SCHEMA_VERSION,
  OBJECT_ID_PATTERN,
  makeObjectId,
  parseObjectId,
  objectIdHex,
  type Snapshot,
  type SnapshotManifest,
  type TableManifest,
  type Commit,
  type CommitAuthor,
  type Branch,
  DEFAULT_BRANCH,
  type GraphDiff,
  type ModifiedSymbol,
  // CAS
  type ContentAddressedStore,
  ObjectNotFoundError,
  putJson,
  getJson,
  canonicalJsonStringify,
  FsCAS,
  type FsCASOptions,
  // Snapshot
  type RowSource,
  type RowSink,
  type GraphRow,
  synthesizeEdgeId,
  serializeSnapshot,
  type SerializeSnapshotOptions,
  type SerializeSnapshotResult,
  type SnapshotStats,
  materializeSnapshot,
  type MaterializeSnapshotOptions,
  type MaterializeSnapshotResult,
  // History
  createCommit,
  readCommit,
  type CreateCommitOptions,
  type CreateCommitResult,
  createBranch,
  deleteBranch,
  setHead,
  getHead,
  listBranches,
  readHead,
  writeHeadBranch,
  writeHeadDetached,
  resolveHeadCommit,
  type HeadState,
  type BranchRefsOptions,
  walkCommits,
  findLowestCommonAncestor,
  type WalkCommitsOptions,
  type CommitLogEntry,
  // Diff
  diffSnapshots,
  type DiffSnapshotsOptions,
  diffSemantic,
  type SemanticDiff,
  type SymbolRef,
  type ClassifiedModification,
  type SemanticChangeKind,
  type SignatureChange,
  // Merge
  threeWayMerge,
  type ThreeWayMergeOptions,
  type ThreeWayMergeResult,
  type MergeConflict,
  type MergeStats,
  type ConflictReason,
  // GC
  gc,
  collectReachableObjects,
  type GcOptions,
  type GcResult,
  type CollectReachableOptions,
} from 'codragraph-graphstore';
