#!/usr/bin/env node
/**
 * Render the JSON output of `codragraph diff --semantic --json` as a Markdown
 * PR comment. Reads the diff payload, emits a sticky-comment-marked Markdown
 * document on stdout. Designed to be sub-second so the GitHub Action stays
 * responsive on every PR push.
 *
 * Usage:  node format-comment.mjs <diff.json> <comment-marker>
 */
import fs from 'node:fs';

const [, , diffPath, markerArg] = process.argv;
if (!diffPath) {
  console.error('Usage: format-comment.mjs <diff.json> [comment-marker]');
  process.exit(2);
}

const marker = markerArg || '<!-- codragraph-pr-review -->';
const data = JSON.parse(fs.readFileSync(diffPath, 'utf8'));
const d = data.semantic || {};

const counts = {
  addedAPIs: (d.addedAPIs || []).length,
  removedAPIs: (d.removedAPIs || []).length,
  classifiedModifications: (d.classifiedModifications || []).length,
  addedProcesses: (d.addedProcesses || []).length,
  removedProcesses: (d.removedProcesses || []).length,
};
const totalChanges = Object.values(counts).reduce((a, b) => a + b, 0);

// Risk heuristic: removed APIs and signature/visibility flips matter most;
// pure additions are usually low-risk.
const breaking =
  counts.removedAPIs +
  (d.classifiedModifications || []).filter(
    (m) => m.signatureChange?.parameterCountChanged || m.visibilityFlip,
  ).length;
let risk = 'LOW';
if (breaking >= 5 || counts.removedProcesses >= 3) risk = 'CRITICAL';
else if (breaking >= 2 || counts.removedProcesses >= 1) risk = 'HIGH';
else if (breaking >= 1 || totalChanges >= 10) risk = 'MEDIUM';

const out = [];
out.push(marker);
out.push('## CodraGraph PR Review — Structural Diff');
out.push('');
out.push(`**Risk:** ${risk}`);
out.push('');
out.push(`**Base:** \`${data.from?.ref || data.from?.commit || '?'}\``);
out.push(`**Head:** \`${data.to?.ref || data.to?.commit || '?'}\``);
out.push('');

if (totalChanges === 0) {
  out.push('_No semantic changes detected._');
  out.push('');
  out.push(footer());
  process.stdout.write(out.join('\n') + '\n');
  process.exit(0);
}

out.push('### Summary');
out.push('');
out.push('| Change | Count |');
out.push('|--------|------:|');
if (counts.addedAPIs) out.push(`| Added APIs | ${counts.addedAPIs} |`);
if (counts.removedAPIs) out.push(`| Removed APIs | ${counts.removedAPIs} |`);
if (counts.classifiedModifications) out.push(`| Modified | ${counts.classifiedModifications} |`);
if (counts.addedProcesses) out.push(`| Added flows | ${counts.addedProcesses} |`);
if (counts.removedProcesses) out.push(`| Removed flows | ${counts.removedProcesses} |`);
out.push('');

if (counts.removedAPIs > 0) {
  out.push('### ⚠️ Removed APIs');
  out.push('');
  for (const r of (d.removedAPIs || []).slice(0, 20)) {
    out.push(`- \`${r.name || r.id}\` (${r.table})`);
  }
  if (counts.removedAPIs > 20) out.push(`- _… and ${counts.removedAPIs - 20} more_`);
  out.push('');
}

if (counts.addedAPIs > 0) {
  out.push('### Added APIs');
  out.push('');
  for (const r of (d.addedAPIs || []).slice(0, 20)) {
    out.push(`- \`${r.name || r.id}\` (${r.table})`);
  }
  if (counts.addedAPIs > 20) out.push(`- _… and ${counts.addedAPIs - 20} more_`);
  out.push('');
}

if (counts.classifiedModifications > 0) {
  out.push('### Modified symbols');
  out.push('');
  out.push('| Symbol | Table | Changes |');
  out.push('|--------|-------|---------|');
  for (const m of (d.classifiedModifications || []).slice(0, 20)) {
    const parts = [...(m.changes || [])];
    if (m.signatureChange?.parameterCountChanged) {
      parts.push(
        `params ${m.signatureChange.parameterCountChanged.from}→${m.signatureChange.parameterCountChanged.to}`,
      );
    }
    if (m.visibilityFlip) {
      parts.push(`exported ${m.visibilityFlip.from}→${m.visibilityFlip.to}`);
    }
    out.push(`| \`${m.id}\` | ${m.table} | ${parts.join(', ')} |`);
  }
  if (counts.classifiedModifications > 20) {
    out.push(`| _… and ${counts.classifiedModifications - 20} more_ | | |`);
  }
  out.push('');
}

if (counts.addedProcesses > 0 || counts.removedProcesses > 0) {
  out.push('### Execution flows');
  out.push('');
  for (const r of d.addedProcesses || []) out.push(`- ➕ \`${r.name || r.id}\``);
  for (const r of d.removedProcesses || []) out.push(`- ➖ \`${r.name || r.id}\``);
  out.push('');
}

out.push(footer());
process.stdout.write(out.join('\n') + '\n');

function footer() {
  return (
    '— Generated by ' +
    '[`codragraph diff --semantic`](https://github.com/AnitChaudhry/CodraGraph). ' +
    'For a deep human-readable review, ask Claude with the `codragraph-pr-review` skill.'
  );
}
